### ISSUE TITLE
add site links to README/AV docs

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/shf-project#204]
I know you have this planned (was talking with @weedySeaDragon yesterday), but just thought I would drop the links in here for my own information management process :-)

* http://shf-project.herokuapp.com/
* http://hitta.sverigeshundforetagare.se/

**Comment by weedySeaDragon** [comment]
- added link to the site in README.md, 
- added link to the heroku site and the production site to documentation page: 
[Deploying to the Deployment and Production Servers](https://github.com/AgileVentures/shf-project/blob/develop/docs/dev/deployment-staging-production.md)
