### ISSUE TITLE
Twitter and Youtube Links point to wrong URL

### ISSUE THREAD

**Issue by roschaefer** [AgileVentures/shf-project#306]
Steps to reproduce:

Twitter
---------
1. Visit http://sverigeshundforetagare.se/
2. Click on the twitter icon on the top left
3. End up at https://twitter.com/sverigeshundftg (does not exist)

Youtube
---------
1. Visit http://sverigeshundforetagare.se/
2. Click on the youtube icon on the top left
3. End up at https://www.google.com/sverigeshundforetagare (certainly not youtube)

EDIT:
Same problem for the linkedin button in the footer

**Comment by patmbolger** [comment]
@roschaefer - thanks for posting this.  I created a bug in pivotal tracker for this.
